"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = ProblemSection;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const InfoCard = ({ title, description, icon, }) => ((0, jsx_runtime_1.jsxs)("div", { className: "group bg-white/80 backdrop-blur-md rounded-2xl p-6 shadow-md border border-gray-200 \r\n  hover:shadow-xl hover:-translate-y-1 hover:border-blue-300 transition duration-300 flex gap-4", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-12 h-12 flex items-center justify-center rounded-xl \r\n    bg-linear-to-r from-blue-100 to-purple-100 shrink-0 \r\n    group-hover:scale-110 transition", children: icon }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-gray-800 mb-1 group-hover:text-blue-600 transition", children: title }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-600 text-sm leading-relaxed", children: description })] })] }));
function ProblemSection() {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "w-full py-24 px-6 md:px-20 relative overflow-hidden", style: {
            backgroundImage: "url('/src/assets/features-bg.png')",
            backgroundSize: "cover",
            backgroundPosition: "center",
        }, children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-linear-to-r from-white/90 via-white/70 to-white/50" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute top-20 left-10 w-40 h-40 bg-blue-300/20 rounded-full blur-3xl" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute bottom-20 right-20 w-52 h-52 bg-purple-300/20 rounded-full blur-3xl" }), (0, jsx_runtime_1.jsxs)("div", { className: "relative", children: [(0, jsx_runtime_1.jsxs)("div", { className: "max-w-3xl mb-14", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-blue-600 text-sm font-semibold mb-2", children: "THE PROBLEM" }), (0, jsx_runtime_1.jsx)("h2", { className: "text-3xl md:text-4xl font-bold text-gray-900 mb-4", children: "Problems with Existing Mental Health Apps" }), (0, jsx_runtime_1.jsx)("div", { className: "w-16 h-1 bg-linear-to-r from-blue-500 to-purple-500 rounded-full mb-6" }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-600 text-lg", children: "Most chatbots only respond to the latest message, ignoring emotional history. Open forums lack the moderation needed to provide a safe space for vulnerable users." }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-400 text-sm mt-2", children: "*This platform does not provide diagnosis or therapy." })] }), (0, jsx_runtime_1.jsxs)("div", { className: "grid md:grid-cols-2 gap-12 items-center", children: [(0, jsx_runtime_1.jsxs)("div", { className: "space-y-6", children: [(0, jsx_runtime_1.jsx)(InfoCard, { title: "Chatbots Lack Context", description: "Most chatbots only respond to the latest message, ignoring emotional history.", icon: (0, jsx_runtime_1.jsx)(lucide_react_1.Bot, { size: 22, strokeWidth: 2, className: "text-blue-600" }) }), (0, jsx_runtime_1.jsx)(InfoCard, { title: "Unsafe Peer Interaction", description: "Open forums lack moderation to provide a safe space for vulnerable users.", icon: (0, jsx_runtime_1.jsx)(lucide_react_1.ShieldAlert, { size: 22, strokeWidth: 2, className: "text-red-500" }) })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex justify-center", children: (0, jsx_runtime_1.jsx)("img", { src: "/src/assets/prob-bg.png", alt: "workflow", className: "w-full max-w-md opacity-95 mix-blend-multiply hover:scale-105 transition duration-500" }) })] }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-400 text-sm mt-16 text-center", children: "*This platform does not provide diagnosis or therapy." })] })] }));
}
//# sourceMappingURL=Prob-sec.js.map