"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = SafetySection;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
// 🔥 Reusable Card
const InfoCard = ({ title, description, icon, }) => {
    return ((0, jsx_runtime_1.jsxs)("div", { className: "group bg-white/80 backdrop-blur-md rounded-2xl p-6 shadow-md border border-gray-200 \r\n    flex items-start gap-4 hover:shadow-xl hover:-translate-y-1 hover:border-blue-300 transition duration-300", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-12 h-12 flex items-center justify-center rounded-xl \r\n      bg-linear-to-r from-blue-100 to-purple-100 shrink-0 \r\n      group-hover:scale-110 transition", children: icon }), (0, jsx_runtime_1.jsxs)("div", { children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-lg font-semibold text-gray-800 mb-1 group-hover:text-blue-600 transition", children: title }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-600 text-sm leading-relaxed", children: description })] })] }));
};
function SafetySection() {
    return ((0, jsx_runtime_1.jsxs)("div", { id: "safety", className: "w-full py-24 px-6 md:px-20 relative overflow-hidden", style: {
            backgroundImage: "url('/src/assets/safe-bg.png')",
            backgroundSize: "cover",
            backgroundPosition: "center",
        }, children: [(0, jsx_runtime_1.jsx)("div", { className: "absolute inset-0 bg-linear-to-r from-white/85 via-white/60 to-white/40" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute top-16 left-10 w-40 h-40 bg-blue-300/20 rounded-full blur-3xl" }), (0, jsx_runtime_1.jsx)("div", { className: "absolute bottom-16 right-10 w-52 h-52 bg-purple-300/20 rounded-full blur-3xl" }), (0, jsx_runtime_1.jsxs)("div", { className: "relative", children: [(0, jsx_runtime_1.jsxs)("div", { className: "text-center max-w-3xl mx-auto mb-14", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-blue-600 text-sm font-semibold mb-2", children: "SAFETY & ETHICS" }), (0, jsx_runtime_1.jsx)("h2", { className: "text-3xl md:text-4xl font-bold text-gray-900 mb-4", children: "Ethical Principles & Safety Measures" }), (0, jsx_runtime_1.jsx)("div", { className: "w-16 h-1 bg-linear-to-r from-blue-500 to-purple-500 rounded-full mx-auto mb-6" }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-600 text-lg", children: "A non-clinical support system designed with clear boundaries and user safety in mind." })] }), (0, jsx_runtime_1.jsx)("div", { className: "flex justify-center mb-12", children: (0, jsx_runtime_1.jsx)("div", { className: "p-6 rounded-full bg-white/70 backdrop-blur-md shadow-md border border-gray-200", children: (0, jsx_runtime_1.jsx)(lucide_react_1.ShieldAlertIcon, { size: 80, className: "text-red-500" }) }) }), (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [(0, jsx_runtime_1.jsx)(InfoCard, { title: "No Diagnosis or Therapy", description: "No medical diagnosis or therapy is provided.", icon: (0, jsx_runtime_1.jsx)(lucide_react_1.ShieldPlus, { size: 22, strokeWidth: 2, className: "text-gray-600" }) }), (0, jsx_runtime_1.jsx)(InfoCard, { title: "Safe & Private Environment", description: "No open public forums or unmoderated discussions.", icon: (0, jsx_runtime_1.jsx)(lucide_react_1.Lock, { size: 22, strokeWidth: 2, className: "text-green-600" }) }), (0, jsx_runtime_1.jsx)(InfoCard, { title: "Crisis Support Redirection", description: "Crisis situations are detected and redirected to external support.", icon: (0, jsx_runtime_1.jsx)(lucide_react_1.AlertTriangle, { size: 22, strokeWidth: 2, className: "text-red-500" }) }), (0, jsx_runtime_1.jsx)(InfoCard, { title: "Human Oversight", description: "AI assistance complements\u2014not replaces\u2014human professionals.", icon: (0, jsx_runtime_1.jsx)(lucide_react_1.Bot, { size: 22, strokeWidth: 2, className: "text-blue-600" }) })] })] })] }));
}
//# sourceMappingURL=Safety-sec.js.map